### PR TITLE
log ncurrent date and time

### PR DESCRIPTION
**Pull request by mamatsa**
description

### CODE REVIEW

**Comment by mamatsa** [comment]
Requested weights: 1
          Number of days: 22
          **Some description**

**Comment by mamatsa** [comment]
- Requested weights: 30
          - Number of days: 12
          description

**Comment by mamatsa** [comment]
- Requested weights: 30  - Number of days: 12  desc

**Comment by mamatsa** [comment]
- Requested weights: 30  - Number of days: 12  **desc**

**Comment by mamatsa** [comment]
- Requested weights: 3232 <br/>- Number of days: 30 <br/>### New comment

**Comment by mamatsa** [comment]
- Requested weights: 99
        - Number of days: 12
        - Description: # Title
* text
* text 2

**Comment by mamatsa** [comment]
- Requested weights: 1
- Number of days: 2
- Description:
*hello* there **my** friend

**Comment by mamatsa** [comment]
- Requested weights: 1
- Number of days: 2

- Description:
des*cription*

**Comment by mamatsa** [comment]
- Requested weights: 12
- Number of days: 22
- Description:
* **hello**

**Comment by mamatsa** [comment]
- Requested weights: 12 - Number of days: 22 - Description: h

**Comment by mamatsa** [comment]
- Requested weights: 12
- Number of days: 22
- Description: d

**Comment by mamatsa** [comment]
Requested weights: 12
Number of days: 22

Description:
## asfds
**hello**
* 1
* 2
* 3
*

**Comment by mamatsa** [comment]
Requested weights: 33
Number of days: 3

Description:
1. 1
2. 2

* 1
* 2
* 3

**Comment by mamatsa** [comment]
Requested weights: 33
Number of days: 3

Description:
`conosole.log(3)`

**Comment by mamatsa** [comment]
- Requested weights: 33
 - Number of days: 3

Description:
`conosole.log(3)`

**Comment by mamatsa** [comment]
- Requested weights: 12
 - Number of days: 24

Description:
```hi``` 
* d

**Comment by mamatsa** [comment]
Requested weights: 12
Number of days: 24


### My solution

**Comment by mamatsa** [comment]
Requested weights: 12
        Number of days: 24


ss

**Comment by mamatsa** [comment]
Requested weights: 12

Number of days: 24


a

**Comment by mamatsa** [comment]
- Requested weights: 12
- Number of days: 24

Description:
s

**Comment by mamatsa** [comment]
- Requested weights: 12
- Number of days: 24
\n
# Description

hello **it's me**

**Comment by mamatsa** [comment]
- Requested weights: 20
- Number of days: 10


description

**Comment by otoarmamatsashvili** [comment]
- Requested weights: 1
- Number of days: 2


new comment

**Pull request merged**
